[book]
authors = ["Matthew J. Berger"]
language = "en"
src = "src"
title = "The Frost Programming Language"

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"
mathjax-support = false
git-repository-url = "https://github.com/matthewjberger/frost"
edit-url-template = "https://github.com/matthewjberger/frost/edit/main/docs/book/{path}"

[output.html.fold]
enable = true
level = 1
