[package]
name = "repl"
version = "0.1.0"
authors = ["Matthew J. Berger <matthewberger@nevada.unr.edu>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
frost = { path = "../" }
rustyline = "8.2.0"